# volume for /usr/src/app/node_modules je ovde jer ne zelim da se oni kopiraju sa mog dev environmenta ???

services:
  client-react-vite:
    image: client-react-vite
    build:
      context: FRONTEND_CONTEXT_DIR
      dockerfile: FRONTEND_DOCKERFILE_PATH
    init: true
    volumes:
      - type: bind
        source: FRONTEND_CONTEXT_DIR
        target: /usr/src/app/ 
      - type: volume # this is volume without source, so on target location is empty folder that's going to be populated after npm build etc
        target: /usr/src/app/node_modules
    networks:
      - frontend
    ports:
      - 5173:5173
  client-react-nginx:
    labels:
      shipyard.primary-route: true
      shipyard.route: '/'
    image: client-react-nginx
    build:
      context: NGINX_CONTEXT_DIR
      dockerfile: NGINX_DOCKERFILE_PATH
    volumes:
      - type: bind
        source: NGINX_CONTEXT_DIR
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped
  api-node:
    labels:
      shipyard.route: '/api/node/'
      shipyard.route.rewrite: true
    image: api-node
    build:
      context: API_NODE_CONTEXT_DIR
      dockerfile: API_NODE_DOCKERFILE_PATH
      target: dev
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped
  api-golang:
    labels:
      shipyard.route: '/api/golang/'
      shipyard.route.rewrite: true
    image: api-golang
    build:
      context: API_GOLANG_CONTEXT_DIR
      dockerfile: API_GOLANG_DOCKERFILE_PATH
      target: dev
    volumes:
      - type: bind
        source: API_GOLANG_CONTEXT_DIR
        target: /usr/src/app/    
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend:

