name: Install Docker
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
 # install-docker:
 #   uses: Mihailo222/GHActions-Reusable-Workflows/.github/workflows/install-docker.yaml@main
 #   with:
 #     os: linux
 #     distribution: ubuntu
 #   secrets:
 #     CHECKOUT_GHE_PAT: ${{ secrets.CHECKOUT_GHE_PAT }} #trigger pipeline
 
  checkout-repos: 
  
    runs-on: ['dp-runner', 'dp-ci', 'self-hosted']   
    
    steps: 
    - name: Check out frontend
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-client-react'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: FRONT
        token: ${{ secrets.CHECKOUT_GHE_PAT }}

    - name: Check out go api.
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-go-api'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: API_GO
        token: ${{ secrets.CHECKOUT_GHE_PAT }}

    - name: Check out node api.
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-node-api'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: NODE_API
        token: ${{ secrets.CHECKOUT_GHE_PAT }}

    - name: Check out docker compose yamls.
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-Deployment-Pipeline'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: DEPLOY_WORKSPACE
        token: ${{ secrets.CHECKOUT_GHE_PAT }}
    
    - name: Edit docker compose file.
      run: |
        sed -i 's|FRONTEND_CONTEXT_DIR|../FRONT/|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|FRONTEND_DOCKERFILE_PATH|../FRONT/Dockerfiles/Dockerfile_dev|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|NGINX_CONTEXT_DIR|../FRONT|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|NGINX_DOCKERFILE_PATH|../FRONT/Dockerfiles/Dockerfile_nginx|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|API_NODE_CONTEXT_DIR|../NODE_API/|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|API_NODE_DOCKERFILE_PATH|../NODE_API/Dockerfile|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|API_GOLANG_CONTEXT_DIR|../API_GO/|g' ./DEPLOY_WORKSPACE/docker-compose.yaml

        sed -i 's|API_GOLANG_DOCKERFILE_PATH|../API_GO/Dockerfile|g' ./DEPLOY_WORKSPACE/docker-compose.yaml
     
    - name: Docker compose up.
      run: |   
        whoami
        sudo docker compose -f ./DEPLOY_WORKSPACE/docker-compose.yaml up -d
        
#    - name: Clean up workspace without destroying directory. 
#      run: |
#        rm -rf ${{ github.workspace }}/*
