name: Install Docker
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
 # install-docker:
 #   uses: Mihailo222/GHActions-Reusable-Workflows/.github/workflows/install-docker.yaml@main
 #   with:
 #     os: linux
 #     distribution: ubuntu
 #   secrets:
 #     CHECKOUT_GHE_PAT: ${{ secrets.CHECKOUT_GHE_PAT }} #trigger pipeline
 
  checkout-repos: 
  
    runs-on: ['dp-runner', 'dp-ci', 'self-hosted']   
    
    steps: 
    - name: Check out frontend
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-client-react'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: FRONT
        token: ${{ secrets.CHECKOUT_GHE_PAT }}

    - name: Check out go api.
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-go-api'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: API_GO
        token: ${{ secrets.CHECKOUT_GHE_PAT }}

    - name: Check out node api.
      uses: actions/checkout@v7
      with:
        repository: 'Mihailo222/DP-node-api'
        ref: 'main'
        fetch-depth: 0 # this checks out the whole history, generally only the last commit is fetched
        path: NODE_API
        token: ${{ secrets.CHECKOUT_GHE_PAT }}
    
    - name: Clean up workspace.
      run: |
        rm -rf ${{ github.workspace }}
        
