name: Install Docker
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  install-docker:
    uses: Mihailo222/GHActions-Reusable-Workflows/.github/workflows/install-docker.yaml@main
    with:
      os: linux
      distribution: ubuntu
    secrets:
      CHECKOUT_GHE_PAT: ${{ secrets.CHECKOUT_GHE_PAT }} #trigger ppl
